# triad-app source revision: 71e1ec43c85868a40d39209f669d4f606155db3d
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pulsecart

resources:
  - https://github.com/triad-platform/triad-app//deploy/k8s?ref=develop

images:
  - name: 971146591534.dkr.ecr.us-east-1.amazonaws.com/triad-app-api-gateway
    newName: 971146591534.dkr.ecr.us-east-1.amazonaws.com/triad-app-api-gateway
    newTag: api-gateway-develop
  - name: 971146591534.dkr.ecr.us-east-1.amazonaws.com/triad-app-orders
    newName: 971146591534.dkr.ecr.us-east-1.amazonaws.com/triad-app-orders
    newTag: orders-develop
  - name: 971146591534.dkr.ecr.us-east-1.amazonaws.com/triad-app-notifications
    newName: 971146591534.dkr.ecr.us-east-1.amazonaws.com/triad-app-notifications
    newTag: notifications-develop
  - name: 971146591534.dkr.ecr.us-east-1.amazonaws.com/triad-app-worker
    newName: 971146591534.dkr.ecr.us-east-1.amazonaws.com/triad-app-worker
    newTag: worker-develop
