apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admission-policy-baseline
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/triad-platform/triad-ci-security.git
    targetRevision: develop
    path: policy/admission/enforced
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
