apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller-prereqs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/triad-platform/triad-kubernetes-platform.git
    targetRevision: develop
    path: platform/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
