apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aws-load-balancer-controller-prereqs.yaml
  - aws-load-balancer-controller.yaml
  - cert-manager.yaml
  - external-dns-prereqs.yaml
  - external-dns.yaml
  - external-secrets-prereqs.yaml
  - external-secrets.yaml
  - nats.yaml
  - observability-baseline.yaml
  - storage-baseline.yaml
