apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: kube-system
  annotations:
    iam.gke.io/gcp-service-account: external-secrets@triad-platform-dev.iam.gserviceaccount.com
