apiVersion: v1
kind: ConfigMap
metadata:
  name: external-secrets-bootstrap
  namespace: kube-system
data:
  provider: azure-key-vault
  vault_uri: https://triad-kv-dev-ce18.vault.azure.net/
  resource_group_name: triad-azure-dev-rg
  cluster_id: /subscriptions/73ecfaac-d482-41a4-89ca-94851eabac2c/resourceGroups/triad-azure-dev-rg/providers/Microsoft.ContainerService/managedClusters/triad-azure-dev-aks
  cluster_name: triad-azure-dev-aks
  oidc_issuer_url: https://eastus.oic.prod-aks.azure.com/8896947d-768a-47aa-a836-54e99ddf0975/ba855a3b-d736-4864-82fe-4ce58e9fc57b/
  kubelet_object_id: 81672f94-ae25-47a6-9a93-06d0470bf8c6
  note: Bootstrap marker for AKS Workload Identity-backed external-secrets.
