apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: observability
type: Opaque
stringData:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: default-sns
      group_wait: 15s
      group_interval: 1m
      repeat_interval: 4h

    receivers:
      - name: default-sns
        sns_configs:
          - topic_arn: arn:aws:sns:us-east-1:971146591534:REPLACE_ME
            subject: PulseCart Dev Alert
            sigv4:
              region: us-east-1
            send_resolved: true
