apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: observability
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::971146591534:role/triad-aws-eks-dev-alertmanager-sns
