apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-config-sync
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: observability-aws-secrets
    kind: SecretStore
  target:
    name: alertmanager-config
    creationPolicy: Merge
  data:
    - secretKey: alertmanager.yml
      remoteRef:
        key: triad/dev/observability/alertmanager
        property: config
