apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: observability
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        fsGroup: 65534
      containers:
        - name: prometheus
          image: prom/prometheus:v2.54.1
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            runAsNonRoot: true
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.enable-lifecycle
          ports:
            - containerPort: 9090
              name: http
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-rules
              mountPath: /etc/prometheus-rules
            - name: prometheus-data
              mountPath: /prometheus
        - name: configmap-reload
          image: ghcr.io/jimmidyson/configmap-reload:v0.15.0
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            runAsNonRoot: true
          args:
            - --volume-dir=/etc/prometheus
            - --volume-dir=/etc/prometheus-rules
            - --webhook-url=http://127.0.0.1:9090/-/reload
            - --webhook-method=POST
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-rules
              mountPath: /etc/prometheus-rules
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-rules
          configMap:
            name: prometheus-rules
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data
